# Semana 2 - Clase 2
#### Temas Selectos Proceso Químicos: Análisis de Datos con Python

# Tuplas

Una tupla es una estructura de datos inmutable y ordenada que permite almacenar una colección de elementos. Los elementos de una tupla se encierran entre paréntesis (), separados por comas.

- Para crear una tupla, encierra los elementos entre paréntesis:

In [ ]:
vector = (3, 4, 1)

Para acceder a los elementos de una tupla, utiliza el índice del elemento entre corchetes, similar a las listas:

In [ ]:
print(vector[1])  # Imprime la posición 1 de la tupla

4


A diferencia de las listas, las tuplas son inmutables, lo que significa que no se pueden modificar una vez creadas. No se pueden agregar, eliminar o cambiar elementos en una tupla existente.

Las tuplas son útiles cuando necesitas almacenar una colección de elementos que no deben modificarse, como coordenadas o datos de configuración.

## Métodos de tuplas

Aunque las tuplas son inmutables, Python proporciona varios métodos útiles para trabajar con ellas:

**count(elemento)**: devuelve el número de veces que aparece un elemento en la tupla.

**index(elemento)**: devuelve el índice de la primera aparición de un elemento en la tupla. Opcionalmente, se puede especificar el inicio y fin de la búsqueda.

**len(tupla)**: aunque no es un método de tupla propiamente dicho, esta función incorporada devuelve la longitud de la tupla.

In [ ]:
mi_tupla = (1, 2, 3, 2, 4, 2)


print (mi_tupla.index(2))

print (mi_tupla.index(2, 2))

print (mi_tupla.index(2, 2, 4))


1
3
3


#  array

Un **array** es una estructura que sirve para **almacenar varios valores relacionados** dentro de una sola variable.  

Un array es una **colección ordenada de datos**.




En programación, un array:
- Guarda **muchos valores**
- Cada valor tiene una **posición (índice)**
- Se puede recorrer y analizar fácilmente

- Un array (normalmente de NumPy) está diseñado para **cálculo numérico eficiente.**

## 📦 Paquetería NumPy

NumPy (Numerical Python) es una biblioteca de Python diseñada para realizar cálculos numéricos de forma eficiente.

Proporciona un objeto ndarray (arreglo N-dimensional), que permite almacenar y manipular grandes volúmenes de datos numéricos de manera rápida, utilizando operaciones vectorizadas sin necesidad de bucles explícitos.

import numpy as np

| Función                         | Descripción                                                    | Ejemplo                            |
| ------------------------------- | -------------------------------------------------------------- | ---------------------------------- |
| `np.array(obj)`                 | Convierte listas, tuplas u objetos similares en un `ndarray`   | `np.array([1, 2, 3])`              |
| `np.zeros(shape)`               | Arreglo lleno de ceros                                         | `np.zeros((2, 3))`                 |
| `np.ones(shape)`                | Arreglo lleno de unos                                          | `np.ones(5)`                       |
| `np.full(shape, fill_value)`    | Arreglo lleno con un valor específico                          | `np.full((3, 3), 7)`               |
| `np.eye(N)`                     | Matriz identidad de tamaño (N \times N)                        | `np.eye(4)`                        |
| `np.arange(start, stop, step)`  | Arreglo con valores equiespaciados                             | `np.arange(0, 10, 2)`              |
| `np.linspace(start, stop, num)` | Arreglo con `num` valores equidistantes entre `start` y `stop` | `np.linspace(0, 1, 5)`             |
| `np.random.rand(d0, d1, ...)`   | Arreglo con valores aleatorios uniformes en ([0, 1))           | `np.random.rand(2, 4)`             |
| `np.random.randn(d0, d1, ...)`  | Arreglo con valores de una distribución normal estándar        | `np.random.randn(3, 3)`            |
| `np.empty(shape)`               | Arreglo sin inicializar (contiene basura de memoria)           | `np.empty((2, 2))`                 |
| `np.reshape(array, new_shape)`  | Cambia la forma de un `ndarray`                                | `np.reshape(np.arange(6), (2, 3))` |


In [ ]:
a = [1, 2, 3] #Listas simples
b = [4, 5, 6]

print(a + b)


[1, 2, 3, 4, 5, 6]


In [ ]:
import numpy as np #cálculos matemáticos eficientes

La función np.array() convierte una lista (o lista de listas, o cualquier secuencia) en un objeto ndarray.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)

[5 7 9]


Producto entre arrays

In [ ]:
A = np.array([[1, 2], [3, 4]])

B = np.array([[2, 0], [1, 2]])

A @ B   # producto matricial--> con listas no es posible directamente


array([[ 4,  4],
       [10,  8]])

Dos listas a arrays

In [ ]:
datos = [[1, 2, 3, 4], [5.3, 62.3, 7, 8]]

In [ ]:
arr = np.array(datos)
print(arr)

[[ 1.   2.   3.   4. ]
 [ 5.3 62.3  7.   8. ]]


  Otra función que nos permite crear un array NumPy es
  `numpy.arange`. Esta función genera un conjunto de números entre un valor de inicio y uno final, pudiendo especificar un incremento entre los valores.

In [ ]:
arr1 = np.arange(1,10,.05)

In [ ]:
print(arr1)

[1.   1.05 1.1  1.15 1.2  1.25 1.3  1.35 1.4  1.45 1.5  1.55 1.6  1.65
 1.7  1.75 1.8  1.85 1.9  1.95 2.   2.05 2.1  2.15 2.2  2.25 2.3  2.35
 2.4  2.45 2.5  2.55 2.6  2.65 2.7  2.75 2.8  2.85 2.9  2.95 3.   3.05
 3.1  3.15 3.2  3.25 3.3  3.35 3.4  3.45 3.5  3.55 3.6  3.65 3.7  3.75
 3.8  3.85 3.9  3.95 4.   4.05 4.1  4.15 4.2  4.25 4.3  4.35 4.4  4.45
 4.5  4.55 4.6  4.65 4.7  4.75 4.8  4.85 4.9  4.95 5.   5.05 5.1  5.15
 5.2  5.25 5.3  5.35 5.4  5.45 5.5  5.55 5.6  5.65 5.7  5.75 5.8  5.85
 5.9  5.95 6.   6.05 6.1  6.15 6.2  6.25 6.3  6.35 6.4  6.45 6.5  6.55
 6.6  6.65 6.7  6.75 6.8  6.85 6.9  6.95 7.   7.05 7.1  7.15 7.2  7.25
 7.3  7.35 7.4  7.45 7.5  7.55 7.6  7.65 7.7  7.75 7.8  7.85 7.9  7.95
 8.   8.05 8.1  8.15 8.2  8.25 8.3  8.35 8.4  8.45 8.5  8.55 8.6  8.65
 8.7  8.75 8.8  8.85 8.9  8.95 9.   9.05 9.1  9.15 9.2  9.25 9.3  9.35
 9.4  9.45 9.5  9.55 9.6  9.65 9.7  9.75 9.8  9.85 9.9  9.95]


En NumPy, es posible convertir un array de un tipo de dato a otro de forma explícita usando el método astype() del ndarray.

In [ ]:
arr2 = np.array([1, 2, 3, 4, 5])

In [ ]:
print(arr2.dtype)

int64


In [ ]:
float_arr = arr2.astype(float)
print(float_arr)

[1. 2. 3. 4. 5.]


De float a enteros

In [ ]:
f = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [ ]:
f_int = f.astype(int)
print(f_int)

[ 3 -1 -2  0 12 10]


De números a letras

In [ ]:
a = np.array([10, 20, 30])
b = a.astype(str)

print(b)


['10' '20' '30']


Tipo de Funciones en NumPy

Álgebra lineal

| Función NumPy           | Descripción                     | Ejemplo                 |
| ----------------------- | ------------------------------- | ----------------------- |
| `np.dot(a, b)`          | Producto escalar o matricial    | `np.dot([1,2], [3,4])`  |
| `np.matmul(a, b)`       | Producto matricial explícito    | `np.matmul(A, B)`       |
| `a @ b`                 | Operador equivalente a `matmul` | `A @ B`                 |
| `np.linalg.norm(a)`     | Norma (longitud) del vector     | `np.linalg.norm([3,4])` |
| `np.linalg.inv(A)`      | Matriz inversa (si existe)      | `np.linalg.inv(A)`      |
| `np.linalg.det(A)`      | Determinante de una matriz      | `np.linalg.det(A)`      |
| `np.linalg.eig(A)`      | Autovalores y autovectores      | `np.linalg.eig(A)`      |
| `np.linalg.solve(A, b)` | Resuelve sistema lineal (Ax=b)  | `np.linalg.solve(A, b)` |


Funciones matemáticas elemento a elemento

| Función NumPy | Descripción       | Ejemplo           |
| ------------- | ----------------- | ----------------- |
| `np.exp(a)`   | Exponencial       | `np.exp([1,2])`   |
| `np.log(a)`   | Logaritmo natural | `np.log([1,2])`   |
| `np.sqrt(a)`  | Raíz cuadrada     | `np.sqrt([4,9])`  |
| `np.abs(a)`   | Valor absoluto    | `np.abs([-1,-2])` |
| `np.sin(a)`   | Seno              | `np.sin(np.pi/2)` |


Estadísticas

| Función NumPy         | Descripción                        | Ejemplo                        |
| --------------------- | ---------------------------------- | ------------------------------ |
| `np.sum(a)`           | Suma todos los elementos del array | `np.sum([1, 2, 3])`            |
| `np.mean(a)`          | Media aritmética                   | `np.mean([1, 2, 3])`           |
| `np.std(a)`           | Desviación estándar                | `np.std([1, 2, 3])`            |
| `np.var(a)`           | Varianza                           | `np.var([1, 2, 3])`            |
| `np.min(a)`           | Valor mínimo                       | `np.min([3, 1, 2])`            |
| `np.max(a)`           | Valor máximo                       | `np.max([3, 1, 2])`            |
| `np.median(a)`        | Mediana                            | `np.median([1, 3, 5])`         |
| `np.percentile(a, q)` | Percentil `q`                      | `np.percentile([1,2,3,4], 75)` |


Búsqueda y ordenamiento

| Función NumPy   | Descripción                     | Ejemplo                |
| --------------- | ------------------------------- | ---------------------- |
| `np.argmin(a)`  | Índice del valor mínimo         | `np.argmin([3,1,2])`   |
| `np.argmax(a)`  | Índice del valor máximo         | `np.argmax([3,1,2])`   |
| `np.sort(a)`    | Ordena los elementos del array  | `np.sort([3,1,2])`     |
| `np.argsort(a)` | Índices que ordenarían el array | `np.argsort([3,1,2])`  |
| `np.unique(a)`  | Valores únicos (sin duplicados) | `np.unique([1,2,2,3])` |


Ejercicio: Con las matrices A y B:


$A =
\begin{pmatrix}
2 & 4 & 6 \\
4 & 5 & 7 \\
6 & 7 & 9
\end{pmatrix}
$


$ B =
\begin{pmatrix}
1 & 2 & 3 \\
0 & 1 & 4 \\
5 & 6 & 0
\end{pmatrix}$


- Calcula el producto matricial

-  Calcula la transpuesta de A y B

- Verifica si A es simétrica

- Calcula la inversa de B (si existe) y comprueba si es su inversa.

In [ ]:
A = np.array([
    [2, 4, 6],
    [4, 5, 7],
    [6, 7, 9]
])

B = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
])

In [ ]:
c = np.dot(A,B)
print(c)


[[32 44 22]
 [39 55 32]
 [51 73 46]]


In [ ]:
A_T = A.T
B_T = B.T
print("\nTranspuesta de A:")
print(A_T)
print("\nTranspuesta de B:")

print(B_T)


Transpuesta de A:
[[2 4 6]
 [4 5 7]
 [6 7 9]]

Transpuesta de B:
[[1 0 5]
 [2 1 6]
 [3 4 0]]


In [ ]:
simetria = np.array_equal(A, A.T)

# Diccionarios

Un **diccionario** es una estructura de datos que permite **guardar información en pares**:
**clave → valor**.

- A diferencia de las listas (que usan posiciones), los diccionarios usan **nombres (claves)** para acceder a los datos.




Un diccionario funciona como:
- un **diccionario real** (palabra → significado)
- o una **tabla con etiquetas**


## Métodos de diccionarios

Los diccionarios en Python tienen varios métodos incorporados para manipular y acceder a los elementos. Algunos métodos comunes son:

- **keys()**: devuelve una vista de todas las claves del diccionario.
- **values()**: devuelve una vista de todos los valores del diccionario.
- **items()**: devuelve una vista de todos los pares clave-valor del diccionario.
- **update(otro_diccionario)**: actualiza el diccionario con los pares clave-valor de otro diccionario.

Una forma de crear un diccionario es utilizando llaves "{}" y signos de dos puntos ":" para separar claves y valores:

In [ ]:
reactor = {
    "tipo": "CSTR",
    "volumen": 5.0,
    "temperatura": 350,
    "presion": 2.5
}
reactor

{'tipo': 'CSTR', 'volumen': 5.0, 'temperatura': 350, 'presion': 2.5}

Se puede acceder a los elementos, insertarlos o formar conjuntos con ellos utilizando la misma sintaxis que para acceder a los elementos de una lista:

In [ ]:
print(reactor["temperatura"])


350


In [ ]:
reactor["temperatura"] = 360 #Modifica la temperatura
reactor["conversion"] = 0.75 #Agrega un nuevo elemento


In [ ]:
print(reactor)

{'tipo': 'CSTR', 'volumen': 5.0, 'temperatura': 360, 'presion': 2.5, 'conversion': 0.75}


¿Para qué usar diccionarios?

En Ingeniería Química son ideales para:

- Guardar propiedades de un sistema

- Almacenar parámetros de un proceso

- Organizar resultados por nombre

- Evitar confusiones con posiciones

In [ ]:
propiedades = {
    "densidad": 998,
    "viscosidad": 0.001,
    "Cp": 4.18
}
print(propiedades)

{'densidad': 998, 'viscosidad': 0.001, 'Cp': 4.18}


| Lista                      | Diccionario                 |
| -------------------------- | --------------------------- |
| Usa índices (0,1,2)        | Usa claves                  |
| Ordenada                   | No depende del orden        |
| Ideal para datos repetidos | Ideal para datos con nombre |


# Funciones en Python

Las **funciones** son el método **más importante** en Python para **organizar**, **reutilizar** y **simplificar** el código.

Regla general:  
Si un mismo código se va a usar **más de una vez**, conviene escribir una **función**.

---

## 1. ¿Qué es una función?

Una **función** es un bloque de código que:
- Realiza una tarea específica
- Tiene un nombre
- Puede recibir datos de entrada
- Puede devolver un resultado


Las funciones permiten:
- Evitar repetir código
- Hacer el programa más claro
- Facilitar correcciones y cambios
- Organizar cálculos complejos



En Python, las funciones se declaran con la palabra clave **`def`**, contiene un bloque de código, con un uso opcional de la palabra clave return.



In [ ]:
def sumar(a, b): #Lo que se encuentra dentro de los parentesis son los parámetros de entrada
    x = a + b
    return x

¿Cómo usar la función?

In [ ]:
sumar(3,5)

8

Las funciones pueden recibir información.

In [ ]:
def imprimir_temperatura(T):
    print("La temperatura es:", T)


In [ ]:
imprimir_temperatura(350)


La temperatura es: 350


Ejemplo: Función para obtener la conversión

In [ ]:
def calcular_conversion(A0, A):
    conversion = (A0 - A) / A0
    return conversion


In [ ]:
X = calcular_conversion(10, 3)
print(X)


0.7


### Funciones con un número variable de argumentos (*).

In [13]:
def suma_variable(*numeros):
    total = 0
    for numero in numeros:
        total += numero
    return total



print(suma_variable(4, 5, 6, 7))

22


Código para calcular el promedio de datos

In [7]:
def promedio(*datos):
  suma = sum(datos)
  total = len(datos)
  res = suma / total
  return res

In [8]:
promedio(3,5,6,7)

5.25

## Funciones anónimas (lambda)

Python permite crear funciones anónimas o funciones lambda, que son funciones sin nombre definidas en una sola línea. Se utilizan comúnmente para funciones pequeñas y concisas

In [9]:
def sumar_2(x):
    sumar= x+2
    return sumar

In [10]:
sumar_2(3)

5

In [11]:
sumar =lambda x: x + 2
print(sumar(3))

5


## Documentación de funciones (docstrings)

Es una buena práctica documentar nuestras funciones utilizando docstrings.

Los docstrings son cadenas de texto que describen el propósito, los parámetros y el valor de retorno de una función. Se colocan inmediatamente después de la definición de la función y se encierran entre triples comillas dobles

In [12]:
def area_rectangulo(base, altura):
    """
    Calcula el área de un rectángulo.


    Args:
        base (float): La base del rectángulo.
        altura (float): La altura del rectángulo.


    Returns:
        float: El área del rectángulo.
    """
    return base * altura

Buenas prácticas:

- Usar nombres claros
- Una función = una tarea
- Evitar funciones muy largas
- Usar return cuando se necesita un resultado